# Jekyll configuration for GitHub Pages

# Site settings
title: "Hear Me Out"
description: "Interactive evaluation and bias discovery platform for speech-to-speech conversational AI"
author: "Shree Harsha Bokkahalli Satish, Gustav Eje Henter, Éva Székely"
url: "https://shreeharsha-bs.github.io"
baseurl: "/Hear-Me-Out"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Minima theme settings
minima:
  social_links:
    github: shreeharsha-bs

# Exclude directories and files that shouldn't be processed by Jekyll
exclude:
  - checkpoints/
  - seed-vc/
  - src/
  - tests/
  - tools/
  - requirements/
  - recordings/
  - reconstructed/
  - local_server_requirements.txt
  - local_vc_server.py
  - test_vc_setup.py
  - start_local_vc_server.sh
  - "*.py"
  - __pycache__/
  - "*.pyc"
  - .git/
  - .gitignore
  - .gitmodules
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - Modal_serving_moshi.md
  - VOICE_CONVERSION_README.md
  - EVAL.md

# Include the main documentation files and assets
include:
  - README.md
  - LICENSE
  - assets/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific settings
repository: shreeharsha-bs/Hear-Me-Out

# Enable GitHub flavored markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
